### PR TITLE
fix(reference) support reference import lookup

### PR DESCRIPTION
**Pull request by basarat**
refs https://github.com/teppeis/typescript-simple/issues/15

### CODE REVIEW

**Comment by teppeis** [comment]
@basarat LGTM!

**Comment by basarat** [comment]
@teppeis is `typescript-1.5` branch on NPM?

**Comment by basarat** [comment]
PS: thanks for adding me as a collab :heart:

**Comment by teppeis** [comment]
oh, sorry. this pr is for 1.5...

**Comment by basarat** [comment]
> oh, sorry. this pr is for 1.5...

Yeah. Reason is that TS 1.4 completely bails and doesn't give any output considering this a syntactic error. 

TS 1.5 on the other hand does give an output.

**Comment by teppeis** [comment]
@basarat not yet on npm. WIP in #4.

**Comment by basarat** [comment]
Cool. Fortunately `<reference` tags are not *required* anymore now that we tsconfig. So #15 can wait a bit longer.

**Comment by teppeis** [comment]
@basarat thanks for your investigation!
I'll complete #4 and ship it as v2.0.0-alpha after https://github.com/Microsoft/TypeScript/pull/2484 is merged.

**Comment by midinastasurazz** [comment]
Does `typescript-simple` support `tsconfig.json`? In particular does it respect `files` specified? I would like to avoid referencing `.d.ts` files using `/// <reference path="..." />` and instead specify them in `files` in `tsconfig.json`. Is that possible?

**Comment by teppeis** [comment]
@midinastasurazz `typescript-simple` doesn't support for referencing `.d.ts`. sorry.

**Comment by midinastasurazz** [comment]
@teppeis Thanks for the info. What about [`tsconfig.json`](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json)? Could the `files` option be used for referencing `.d.ts` files? It seems to be supported by TypeScript since 1.5. So does `typescript-simple` essentially disregard `tsconfig.json`?

**Comment by teppeis** [comment]
@midinastasurazz Loading tsconfig.json is a function of `tsc` command, not of TypeScript Language.
Even if `typescript-simple` can load it, doesn't support for multiple files structure including d.ts.

**Pull request merged**
